USE [TennisMembership] ;

CREATE TABLE Member (
		MID INT PRIMARY KEY IDENTITY ,
		Email VARCHAR(50) UNIQUE NOT NULL ,
		Pass  VARCHAR(100) NOT NULL ,
		Name  VARCHAR(50)  NOT NULL ,
		MobileContact VARCHAR(11) ,
		Address VARCHAR (100) ,
		DOB DATE NOT NULL ,
		CHECK (MobileContact LIKE('%[0-9]%'))
);

CREATE TABLE Coach (
		CID INT PRIMARY KEY IDENTITY ,
		Email VARCHAR(50) UNIQUE NOT NULL ,
		Pass  VARCHAR(100) NOT NULL ,
		Name  VARCHAR(50)  NOT NULL ,
		Contact VARCHAR(11) ,
		Experience INT ,
		Biography NVARCHAR(500) ,
		CHECK (Contact LIKE('%[0-9]%'))
);

CREATE TABLE Admin (
		AID INT PRIMARY KEY IDENTITY ,
		Email VARCHAR(50) UNIQUE NOT NULL ,
		Pass  VARCHAR(100) NOT NULL 
);

CREATE TABLE Schedule (
		ID INT PRIMARY KEY IDENTITY ,
		Event_Name VARCHAR(50) NOT NULL ,
		Date DATE NOT NULL ,
		Location VARCHAR (100) NOT NULL ,
		CoachID INT NOT NULL UNIQUE ,
		FOREIGN KEY (CoachID) REFERENCES Coach (CID) 
);